# add the linters you want stickler to use for this project
linters:
    stylelint:
      # indicate where is the config file for stylelint
      config: 'stylelint.config.js'
  
  # PLEASE DO NOT enable auto fixing options
  # if you need extra support from you linter - do it in your local env as described in README for this config
  
  # find full documentation here: https://stickler-ci.com/docs
  - name: Setup Node.js for use with actions
  uses: actions/setup-node@v1.1.0
  with:
    # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0, lts
    version: # optional, default is 10.x
    # Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN
    registry-url: # optional
    # Optional scope for authenticating against scoped registries
    scope: # optional